name: Build and deploy Node.js app to Azure Web App - pa4-24030006

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: pa4-24030006
  APP_PATH: webapp
  NODE_VERSION: 20.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.APP_PATH }}/package-lock.json

      - name: Install web app dependencies
        working-directory: ${{ env.APP_PATH }}
        run: npm ci

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C7846F453984C72BE3210A89B3F4829 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_12B0097E0574440F8B1747527ACC357E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39694049D00B4F50A437AE448EA9B1CA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.APP_PATH }}
